services:
  - type: web
    name: app-igreja-analia
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npx serve -s dist
    build:
      envVars:
        - key: NODE_VERSION
          value: 22
    envVars:
      - key: NODE_VERSION
        value: 22
    staticPublishPath: dist
